export const ACCIDENT_STATUS = {
    REPORTED: "REPORTED",
    RESPONDING: "RESPONDING",
    CLEARED: "CLEARED"
};

export const ACCIDENT_STATUS_ENUM = Object.values(ACCIDENT_STATUS);

export const SEVERITY = {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
    CRITICAL: "CRITICAL"
};

export const SEVERITY_ENUM = Object.values(SEVERITY);

export const AMBULANCE_STATUS = {
    AVAILABLE: "AVAILABLE",
    DISPATCHED: "DISPATCHED",
    MAINTENANCE: "MAINTENANCE"
};

export const AMBULANCE_STATUS_ENUM = Object.values(AMBULANCE_STATUS);
