import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Bell,
  Radio,
  CheckCircle2,
  AlertTriangle,
  Info,
  Clock,
  MapPin,
  X,
  Shield,
  Layers,
  ChevronRight,
} from 'lucide-react';
import { SystemAlert } from '../../types';
import apiClient from '../../services/apiClient';
import { reverseGeocode } from '../../utils/location';

export const SystemAlertsPage: React.FC = () => {
  const navigate = useNavigate();
  const [alerts, setAlerts] = useState<SystemAlert[]>([]);
  const [typeFilter, setTypeFilter] = useState<'ALL' | 'CRITICAL' | 'WARNING' | 'INFO' | 'RESOLVED'>('ALL');
  const [isLoading, setIsLoading] = useState(true);

  React.useEffect(() => {
    const fetchAlerts = async () => {
      try {
        const response = await apiClient.get('/alerts/active');
        if (response.data.success && response.data.data) {
          const formatted = await Promise.all(response.data.data.map(async (item: any) => {
            let addressStr = 'Prayagraj';
            const coords = item.location?.coordinates;
            if (coords && coords.length === 2) {
              try {
                const geo = await reverseGeocode(coords[1], coords[0]);
                addressStr = geo.address || geo.city || addressStr;
              } catch (e) {
                console.error("Geocoding error", e);
              }
            }

            return {
              id: item._id,
              type: item.type || 'CRITICAL',
              title: item.type + ' Alert',
              message: item.message || 'No description provided.',
              location: addressStr,
              timestamp: new Date(item.created_at || Date.now()).toISOString(),
              isRead: false,
              acknowledged: false,
              actionUrl: '/authority/overview'
            };
          }));
          setAlerts(formatted);
        }
      } catch (error) {
        console.error('Failed to fetch alerts:', error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchAlerts();
  }, []);

  const handleAcknowledge = (id: string) => {
    setAlerts((prev) =>
      prev.map((a) => (a.id === id ? { ...a, acknowledged: true, isRead: true } : a))
    );
  };

  const filteredAlerts = alerts.filter((a) =>
    typeFilter === 'ALL' ? true : a.type === typeFilter
  );

  return (
    <div className="space-y-6 pb-20 pt-2 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-mono uppercase tracking-widest text-[#ff5252] bg-[#93000a]/30 px-2 py-0.5 rounded border border-[#ffb4ab]/30">
              REAL-TIME INCIDENT NOTIFICATIONS
            </span>
          </div>
          <h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">
            System & Road Network Alerts
          </h1>
          <p className="text-xs md:text-sm text-[#8c90a1]">
            Automated alerts generated by smart computer vision, environmental flood sensors, and road patrol data info.
          </p>
        </div>

        {/* Filter Tabs */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none bg-[#151b2b] p-1 rounded-xl border border-white/10">
          {(['ALL', 'CRITICAL', 'WARNING', 'INFO', 'RESOLVED'] as const).map((t) => (
            <button
              key={t}
              onClick={() => setTypeFilter(t)}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono transition-colors ${
                typeFilter === t
                  ? 'bg-[#0066ff] text-white font-bold'
                  : 'text-[#8c90a1] hover:text-white'
              }`}
            >
              {t}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts Feed */}
      <div className="space-y-3">
        {filteredAlerts.map((alert) => (
          <div
            key={alert.id}
            className={`p-5 rounded-2xl border transition-all shadow-lg ${
              alert.type === 'CRITICAL'
                ? 'bg-[#151b2b] border-[#ff5252]/40 border-l-4 border-l-[#ff5252]'
                : alert.type === 'WARNING'
                ? 'bg-[#151b2b] border-[#ffa000]/40 border-l-4 border-l-[#ffa000]'
                : alert.type === 'RESOLVED'
                ? 'bg-[#151b2b] border-emerald-500/40 border-l-4 border-l-emerald-500'
                : 'bg-[#151b2b] border-white/10 border-l-4 border-l-[#00daf3]'
            }`}
          >
            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3">
              <div className="space-y-1.5 flex-1">
                <div className="flex items-center gap-2">
                  <span
                    className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded ${
                      alert.type === 'CRITICAL'
                        ? 'bg-[#93000a] text-[#ffdad6]'
                        : alert.type === 'WARNING'
                        ? 'bg-[#ffa000]/20 text-[#ffa000]'
                        : alert.type === 'RESOLVED'
                        ? 'bg-emerald-950 text-emerald-300'
                        : 'bg-[#00e3fd]/20 text-[#00daf3]'
                    }`}
                  >
                    {alert.type}
                  </span>
                  <span className="font-mono text-xs text-[#8c90a1]">{alert.id}</span>
                  <span className="text-xs font-mono text-[#8c90a1] flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {alert.timestamp}
                  </span>
                </div>

                <h3 className="text-base font-bold text-white">{alert.title}</h3>
                <p className="text-xs text-[#c2c6d8] leading-relaxed">{alert.message}</p>

                <div className="flex items-center gap-1.5 text-xs text-[#8c90a1] font-mono pt-1">
                  <MapPin className="w-3.5 h-3.5 text-[#00daf3]" />
                  <span>{alert.location}</span>
                </div>
              </div>

              <div className="flex items-center gap-2 shrink-0 self-end sm:self-center">
                {!alert.acknowledged && (
                  <button
                    onClick={() => handleAcknowledge(alert.id)}
                    className="px-3.5 py-1.5 rounded-xl bg-[#191f2f] hover:bg-[#242a3a] border border-white/10 text-xs font-mono text-[#00daf3] transition-colors"
                  >
                    Acknowledge
                  </button>
                )}
                {alert.relatedId && (
                  <button
                    onClick={() => navigate('/authority/priority')}
                    className="px-3.5 py-1.5 rounded-xl bg-[#b3c5ff] hover:bg-[#dae1ff] text-[#002b75] font-bold text-xs font-mono transition-all flex items-center gap-1"
                  >
                    <span>View Asset</span>
                    <ChevronRight className="w-3 h-3" />
                  </button>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
